#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;
int main ()
{
    cout << "------Welcome to the Number Guessing Game------" << endl;

    srand(time(0));                                         // This is the function for generating a random number.
    int num = rand() % 100 + 1;                            // Generates a random integer between 1 and 100.
    int guess = 0;                                        // Initializing user's guess as zero.
    int x = 1;
    cout << "Enter the choice: " << endl;
    cout << "1. Play\n2. Exit" << endl;
    int choice;
    cin >> choice;

    switch (choice)
    {
    case 1:
        cout << "Instructions before playing this game: \n";
        cout << "1. There will be a random number generated by the system, you've to guessed it coreectly. \n2. There are 5 turns in the game.\n3. The random number is in between 1 to 100." << endl;

        do {
        cout << "Enter your guess: ";
        cin >> guess;                                    // Taking input from the user.

        if (guess < num) {                              // Condition to check  whether the entered number is less than the generated number.
            cout << "Too Low!" << endl;
        }
        else if (guess > num) {                        //  If the user enters a number greater than the generated number.
            cout << "Too High!" << endl;
        }
        else {
            cout << "Correct!" << endl;
            x = 0;
        }
    }
    while (x == 1);

    cout << "Congratulations! You have won this game." << endl;
    
    break;

    case 2:
        cout << "Exiting the game..." << endl;             // Exits the game if user chooses option 2.
        break;

    default:
        break;
    }
    
    return 0;

}
